# Generated by Django 5.2.9 on 2026-01-19 18:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackedcompany',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='deadline',
            field=models.DateField(default=datetime.date(2026, 1, 19)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trackedcompany',
            name='career_url',
            field=models.URLField(default=datetime.date(2026, 1, 19)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.company'),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracked_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.trackedcompany')),
            ],
        ),
    ]
